name: floaty
description: Best paragliding flight loggin app in the world.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.1
  uuid: ^4.4.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  floaty_client:
    path: lib/generated
  cookie_jar: ^4.0.8
  csv: ^6.0.0
  path_provider: ^2.1.5
  file_saver: ^0.2.14
  fl_chart: ^0.70.2
  url_launcher: ^6.2.4
  visibility_detector: ^0.4.0+2
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^1.0.0
  latlong2: ^0.9.0
  web: ^1.1.1
  dropdown_search: ^6.0.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/logo.png
    - assets/images/floaty_laptop_phone.png
    - assets/images/floaty_statistics.png
    - assets/images/coffee-cup.png
    - assets/images/track.png
    - staticwebapp.config.json